apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-v
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app-v
  template:
    metadata:
      labels:
        app: node-app-v
    spec:
      containers:
      - name: node-app-v
        image: ankit12121999/node_v:latest
        ports:
        - containerPort: 5000