apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: NodePort
  selector:
    app: node-app-v
  ports:
    - protocol: TCP
      port: 80  # Exposed port on the Service
      targetPort: 5000  # Port on your application container
      nodePort: 30000  # Optional: specify a specific port, or let Kubernetes assign one